// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byaaliobjjdffkhnxytv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5YWFsaW9iampkZmZraG54eXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjA3MTAsImV4cCI6MjA3MzYzNjcxMH0.Vzihl6kJO8v6eZHQ3r3yBQqOxzj1vZjwiKEMrIANvzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});